export * from './panel-control/ConfirmedCases'
export * from './panel-control/Deaths'
export * from './panel-control/Recovered'
export * from './header/Header'
export * from './lateral-menu/LateralMenu'